# Loads default set of integrations. Do not remove.
default_config:

http:
  login_attempts_threshold: 5
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - https://homeassistant.tommass.com
    - https://ha.tommass.com
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.45 # nginx server"
    - 192.168.2.0/24 # entire home network"

homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Warsaw

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/clock-weather-card/clock-weather-card.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module
    - url: /local/mini-humidifier-bundle.js?v=3.1.1
      type: module

  dashboards:
    lovelace-rooms: # Needs to contain a hyphen (-)
      mode: yaml
      filename: ui/dashboards/rooms.yaml
      title: Rooms
      icon: mdi:home-assistant
      show_in_sidebar: true
      require_admin: false
    lovelace-test: # Needs to contain a hyphen (-)
      mode: yaml
      filename: ui/dashboards/test.yaml
      title: Test
      icon: mdi:home-assistant
      show_in_sidebar: true
      require_admin: false
    lovelace-lights:
      mode: yaml
      filename: ui/dashboards/lights.yaml
      title: Освещение
      icon: mdi:lightbulb-group
      show_in_sidebar: true
      require_admin: false
    lovelace-server:
      mode: yaml
      filename: ui/dashboards/server.yaml
      title: Сервер
      icon: mdi:server
      show_in_sidebar: true
      require_admin: false

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
fan: !include includes/fan.yaml

# sensor: !include includes/sensor.yaml
# switch: !include includes/switch.yaml
# number: !include includes/number.yaml
# humidifier: !include includes/humidifier.yaml

template: !include_dir_merge_list includes/sensor

input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
